import { createContext, useState, useEffect } from "react";
import { BiChip } from "react-icons/bi";
import { IoIosPhonePortrait } from "react-icons/io";
import { FaMicrochip, FaHdd, FaWeightHanging } from "react-icons/fa";
import { MdScreenShare } from "react-icons/md";
import { CgCreditCard } from "react-icons/cg";

const product_01 = require("../../images/products/img13.jpg").default;
const product_02 = require("../../images/products/img14.jpg").default;
const product_03 = require("../../images/products/img15.jpg").default;
const product_04 = require("../../images/products/img16.jpg").default;
const product_05 = require("../../images/products/img17.jpg").default;
const product_06 = require("../../images/products/img18.jpg").default;
const product_07 = require("../../images/products/img19.jpg").default;
const product_08 = require("../../images/products/img20.jpg").default;

const product_09 = require("../../images/products/laptop/img1.jpg").default;
const product_10 = require("../../images/products/laptop/img2.jpg").default;
const product_11 = require("../../images/products/laptop/img3.jpg").default;
const product_12 = require("../../images/products/laptop/img4.jpg").default;
const product_13 = require("../../images/products/laptop/img5.jpg").default;
const product_14 = require("../../images/products/laptop/img6.jpg").default;
const product_15 = require("../../images/products/laptop/img7.jpg").default;
const product_16 = require("../../images/products/laptop/img8.jpg").default;
const product_17 = require("../../images/products/laptop/img9.jpg").default;
const product_18 = require("../../images/products/laptop/img10.jpg").default;
const product_19 = require("../../images/products/laptop/img11.jpg").default;
const product_20 = require("../../images/products/laptop/img12.jpg").default;
const product_21 = require("../../images/products/laptop/img13.jpg").default;

const product_pay_01 = require("../../images/products/pay1.jpg").default;
const product_pay_02 = require("../../images/products/pay2.jpeg").default;
const product_pay_03 = require("../../images/products/pay3.jpg").default;
export const DataContext = createContext();
export const DataLaptop = props => {
  const [products, setProducts] = useState([
    {
      _id: "1",
      images: product_01,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "MacBook Pro 13'' 2020 Touch Bar M1 256GB",
      titledetial: "Macbook",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "34499000",
      del: "3499000₫",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "M1",
      screen: "13.3”",
      ram: "8 GB",
      rom: "256 GB",
      card: "Apple M1",
      weight: "1.4",
      count: 1,
      danhgia: "7 đánh giá",
      hoidap: "629 hỏi đáp",
      hoi: "629",
    },

    {
      _id: "2",
      images: product_02,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "MSI Modern 14 B11MOL 688VN i3 1115G4",
      titledetial: "MSI",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "14999000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Core i3",
      screen: "14.0”",
      ram: "8 GB",
      rom: "256 GB",
      card: "Intel UHD Graphics",
      weight: "1.3",
      count: 1,
      danhgia: "1 đánh giá",
      hoidap: "1793 hỏi đáp",
      hoi: "1793",
    },
    {
      _id: "3",
      images: product_03,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "AVITA Liber V14B CG i7 10510U",
      titledetial: "AVITA",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "21999000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Core i7",
      screen: "14.0”",
      ram: "8 GB",
      rom: "1 TB",
      card: "Intel UHD Graphics 620",
      weight: "1.28",
      count: 1,
      danhgia: "1 đánh giá",
      hoidap: "115 hỏi đáp",
      hoi: "115",
    },
    {
      _id: "4",
      images: product_04,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "Asus TUF Gaming FX506LH HN002T i5 10300H",
      titledetial: "Asus",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "21999000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Core i5",
      screen: "15.6”",
      ram: "8 GB",
      rom: "512 GB",
      card: "GeForce GTX 1650 4GB-GDDR6",
      weight: "2.3",
      count: 1,
      danhgia: "212 đánh giá",
      hoidap: "1922 hỏi đáp",
      hoi: "1922",
    },
    {
      _id: "5",
      images: product_05,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "HP 240 G8 i3 1005G1",
      titledetial: "HP",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "14299000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Core i3",
      screen: "14.0”",
      ram: "8 GB",
      rom: "512 GB",
      card: "Intel UHD Graphics 600",
      weight: "1.47",
      count: 1,
      danhgia: "5 đánh giá",
      hoidap: "1390 hỏi đáp",
      hoi: "1390",
    },
    {
      _id: "6",
      images: product_06,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "Acer Nitro Gaming AN515 56 51N4 i5 11300H",
      titledetial: "Acer",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "23999000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Core i5",
      screen: "15.6”",
      ram: "8 GB",
      rom: "512 GB",
      card: "GeForce GTX 1650 4GB",
      weight: "2.2",
      count: 1,
      danhgia: "7 đánh giá",
      hoidap: "1777 hỏi đáp",
      hoi: "1777",
    },
    {
      _id: "7",
      images: product_07,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "Lenovo Gaming 3 15IHU6 i5 11300H",
      titledetial: "Lenovo",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "25499000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Core i5",
      screen: "15.6”",
      ram: "8 GB",
      rom: "512 GB",
      card: "NVIDIA GeForce RTX 3050 4GB",
      weight: "2.25",
      count: 1,
      danhgia: "1 đánh giá",
      hoidap: "124 hỏi đáp",
      hoi: "124",
    },
    {
      _id: "8",
      images: product_08,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "Asus Zenbook UX425EA KI429T i5 1135G7",
      titledetial: "Asus",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "23999000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Core i5",
      screen: "14.0”",
      ram: "8 GB",
      rom: "512 GB",
      card: "Intel Iris Xe Graphics",
      weight: "1.17",
      count: 1,
      danhgia: "19 đánh giá",
      hoidap: "1496 hỏi đáp",
      hoi: "1496",
    },

    {
      _id: "9",
      images: product_09,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "Laptop Acer Nitro Gaming AN515 57 51G6 i5 11400H",
      titledetial: "Acer",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "25999000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Core i5",
      screen: "15.6”",
      ram: "8 GB",
      rom: "512 GB",
      card: "NVIDIA GeForce RTX3050 4GB",
      weight: "2.2",
      count: 1,
      danhgia: "8 đánh giá",
      hoidap: "1583 hỏi đáp",
      hoi: "1583",
    },
    {
      _id: "10",
      images: product_10,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "Fujitsu CH 9C13A1 i5 1135G7",
      titledetial: "Fujitsu",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "23999000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Core i5",
      screen: "13.3”",
      ram: "8 GB",
      rom: "512 GB",
      card: "Intel Iris Xe Graphics",
      weight: "0.995",
      count: 1,
      danhgia: "1 đánh giá",
      hoidap: "21 hỏi đáp",
      hoi: "21",
    },
    {
      _id: "11",
      images: product_11,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "MSI Gaming GF65 10UE 286VN i5 10500H",
      titledetial: "MSI",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "29699000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Core i5",
      screen: "15.6”",
      ram: "16 GB",
      rom: "512 GB",
      card: "NVIDIA GeForce RTX 3060 Max- Q 6GB",
      weight: "1.86",
      count: 1,
      danhgia: "2 đánh giá",
      hoidap: "193 hỏi đáp",
      hoi: "193",
    },
    {
      _id: "12",
      images: product_12,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "Dell G3 15 3500B i7 10750H",
      titledetial: "Dell",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "31999000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Core i7",
      screen: "15.6”",
      ram: "16 GB",
      rom: "512 GB",
      card: "Nvidia GTX1660Ti 6GB",
      weight: "2.58",
      count: 1,
      danhgia: "2 đánh giá",
      hoidap: "171 hỏi đáp",
      hoi: "171",
    },
    {
      _id: "13",
      images: product_13,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "MSI Gaming Katana GF66 11UC 641VN i7 11800H",
      titledetial: "MSI",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "29999000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Core i7",
      screen: "15.6”",
      ram: "8 GB",
      rom: "512 GB",
      card: "NVIDIA GeForce RTX 3050 4GB",
      weight: "2.1",
      count: 1,
      danhgia: "1 đánh giá",
      hoidap: "33 hỏi đáp",
      hoi: "33",
    },
    {
      _id: "14",
      images: product_14,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "HP Envy 13 ba1030TU i7 1165G7",
      titledetial: "HP",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "30699000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Core i7",
      screen: "13.3”",
      ram: "8 GB",
      rom: "512 GB",
      card: "Card Onboard",
      weight: "1.25",
      count: 1,
      danhgia: "1 đánh giá",
      hoidap: "111 hỏi đáp",
      hoi: "111",
    },
    {
      _id: "15",
      images: product_15,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "Gigabyte Gaming G5 MD i5 11400H",
      titledetial: "Gigabyte",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "29999000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Core i5",
      screen: "15.6”",
      ram: "16 GB",
      rom: "512 GB",
      card: "INVIDIA GeForce RTX3050 Ti 4GB",
      weight: "2.2",
      count: 1,
      danhgia: "1 đánh giá",
      hoidap: "24 hỏi đáp",
      hoi: "24",
    },
    {
      _id: "16",
      images: product_16,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "MSI Pulse GL66 11UDK 255VN i7 11800H",
      titledetial: "MSI",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "33999000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Core i7",
      screen: "15.6”",
      ram: "16 GB",
      rom: "512 GB",
      card: "NVIDIA® GeForce® RTX 3050 Ti 4GB",
      weight: "2.25",
      count: 1,
      danhgia: "1 đánh giá",
      hoidap: "63 hỏi đáp",
      hoi: "63",
    },
    {
      _id: "17",
      images: product_17,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "MSI Gaming Alpha 15 B5EEK 036VN R7 5800H",
      titledetial: "MSI",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "36999000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Ryzen 7",
      screen: "15.6”",
      ram: "16 GB",
      rom: "512 GB",
      card: "AMD Radeon RX 6600M 8GB",
      weight: "2.35",
      count: 1,
      danhgia: "1 đánh giá",
      hoidap: "20 hỏi đáp",
      hoi: "20",
    },
    {
      _id: "18",
      images: product_18,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "Asus Zenbook UX325EA KG363T i5 1135G7",
      titledetial: "Asus",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "24299000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Core i5",
      screen: "13.3”",
      ram: "8 GB",
      rom: "512 GB",
      card: "Intel Iris Xe Graphics",
      weight: "1.1",
      count: 1,
      danhgia: "2 đánh giá",
      hoidap: "539 hỏi đáp",
      hoi: "539",
    },
    {
      _id: "19",
      images: product_19,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "MSI Prestige 14EVO A11M-089VN i7 1185G7",
      titledetial: "MSI",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "29999000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Core i7",
      screen: "14.0”",
      ram: "16 GB",
      rom: "512 GB",
      card: "Intel Iris Xe Graphics",
      weight: "1.29",
      count: 1,
      danhgia: "1 đánh giá",
      hoidap: "62 hỏi đáp",
      hoi: "62",
    },
    {
      _id: "20",
      images: product_20,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "Asus Vivobook E210KA GJ031T N4500",
      titledetial: "Asus",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "7799000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Celeron",
      screen: "11.6”",
      ram: "8 GB",
      rom: "eMMC 128GB",
      card: "Intel UHD Graphics 600",
      weight: "1.1",
      count: 1,
      danhgia: "6 đánh giá",
      hoidap: "88 hỏi đáp",
      hoi: "88",
    },
    {
      _id: "21",
      images: product_21,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "Asus FLow Gaming GV301QC-K6052T R9 5900HS",
      titledetial: "Asus",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "39999000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Ryzen 9",
      screen: "13.4”",
      ram: "16 GB",
      rom: "512 GB",
      card: "Nvidia GeForce RTX3050 4GB",
      weight: "1.3",
      count: 1,
      danhgia: "1 đánh giá",
      hoidap: "40 hỏi đáp",
      hoi: "40",
    },
  ]);

  // Về add cart
  const [cart, setCart] = useState([]);

  const addCart = id => {
    const check = cart.every(item => {
      return item._id !== id;
    });
    if (check) {
      const data = products.filter(product => {
        return product._id === id;
      });
      setCart([...cart, ...data]);
    } else {
      alert("The product has been added to cart.");
    }
  };

  //cart
  useEffect(() => {
    const dataCart = JSON.parse(localStorage.getItem("dataCart"));
    if (dataCart) setCart(dataCart);
  }, []);

  useEffect(() => {
    localStorage.setItem("dataCart", JSON.stringify(cart));
  }, [cart]);

  const value = {
    // sản phẩm
    products: [products, setProducts],
    // cart
    cart: [cart, setCart],
    addCart: addCart,
  };
  return (
    <DataContext.Provider value={value}>
      {" "}
      {props.children}{" "}
    </DataContext.Provider>
  );
};
