import { createContext, useState, useEffect } from "react";
import { BiChip } from "react-icons/bi";
import { IoIosPhonePortrait } from "react-icons/io";
import { FaMicrochip, FaHdd, FaWeightHanging } from "react-icons/fa";
import { MdScreenShare } from "react-icons/md";
import { CgCreditCard } from "react-icons/cg";

const product_01 = require("../../images/products/tablet/img13.jpg").default;
const product_02 = require("../../images/products/tablet/img14.jpg").default;
const product_03 = require("../../images/products/tablet/img15.jpg").default;
const product_04 = require("../../images/products/tablet/img16.jpg").default;
const product_05 = require("../../images/products/tablet/img17.jpg").default;
const product_06 = require("../../images/products/tablet/img18.jpg").default;
const product_07 = require("../../images/products/tablet/img19.jpg").default;
const product_08 = require("../../images/products/tablet/img20.jpg").default;

const product_09 = require("../../images/products/tablet/img1.jpg").default;
const product_10 = require("../../images/products/tablet/img2.jpg").default;
const product_11 = require("../../images/products/tablet/img3.jpg").default;
const product_12 = require("../../images/products/tablet/img4.jpg").default;
const product_13 = require("../../images/products/tablet/img5.jpg").default;
const product_14 = require("../../images/products/tablet/img6.jpg").default;
const product_15 = require("../../images/products/tablet/img7.jpg").default;
const product_16 = require("../../images/products/tablet/img8.jpg").default;
const product_17 = require("../../images/products/tablet/img9.jpg").default;
const product_18 = require("../../images/products/tablet/img10.jpg").default;
const product_19 = require("../../images/products/tablet/img11.jpg").default;
const product_20 = require("../../images/products/tablet/img12.jpg").default;
const product_21 = require("../../images/products/tablet/img13.jpg").default;

const product_pay_01 = require("../../images/products/pay1.jpg").default;
const product_pay_02 = require("../../images/products/pay2.jpeg").default;
const product_pay_03 = require("../../images/products/pay3.jpg").default;
export const DataContext = createContext();
export const DataTablet = props => {
  const [products, setProducts] = useState([
    {
      _id: "1",
      images: product_01,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "Samsung Galaxy Tab A7 Lite",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "4490000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "MediaTek MT8768T",
      screen: "8.7”",
      ram: "83GB",
      rom: "32 GB",
      pin: "5100 mAh",
      count: 1,
      danhgia: "50 đánh giá",
      hoidap: "200 hỏi đáp",
      hoi: "200",
    },

    {
      _id: "2",
      images: product_02,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "iPad 10.2 2020 Wi-Fi + Cellular 128GB",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "15999000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "A12 Bionic",
      screen: "10.2”",
      ram: "3 GB",
      rom: "128 GB",
      count: 1,
      danhgia: "125 đánh giá",
      hoidap: "612 hỏi đáp",
      hoi: "612",
    },
    {
      _id: "3",
      images: product_03,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "Masstel Tab 10 Ultra",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "3490000",
      del: "3790000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Core i7",
      screen: "10.1”",
      ram: "3 GB",
      rom: "32 GB",
      pin: "6000 mAh",
      count: 1,
      danhgia: "78 đánh giá",
      hoidap: "102 hỏi đáp",
      hoi: "102",
    },
    {
      _id: "4",
      images: product_04,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "Masstel Tab 10 4G ",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "3190000",
      del: "3490000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Đang cập nhật",
      screen: "10.1”",
      ram: "2 GB",
      rom: "32 GB",
      pin: "6000 mAh",
      count: 1,
      danhgia: "59 đánh giá",
      hoidap: "205 hỏi đáp",
      hoi: "205",
    },
    {
      _id: "5",
      images: product_05,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "Samsung Galaxy Tab S7 FE",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "13990000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Snapdragon 750G",
      screen: "12.4”",
      ram: "4 GB",
      rom: "64 GB",
      pin: "10090 mAh",
      count: 1,
      danhgia: "10 đánh giá",
      hoidap: "56 hỏi đáp",
      hoi: "56",
    },
    {
      _id: "6",
      images: product_06,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "iPad Air 10.9 2020 Wi-Fi 64GB",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "16799000",
      del: "16999000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "A14 Bionic",
      screen: "10.9”",
      ram: "4 GB",
      rom: "64 GB",
      count: 1,
      danhgia: "156 đánh giá",
      hoidap: "231 hỏi đáp",
      hoi: "231",
    },
    {
      _id: "7",
      images: product_07,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "iPad Air 10.9 2020 Wi-Fi + Cellular 64GB",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "20799000",
      del: "20999000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "A14 Bionic",
      screen: "10.9”",
      ram: "4 GB",
      rom: "64 GB",
      count: 1,
      danhgia: "97 đánh giá",
      hoidap: "137 hỏi đáp",
      hoi: "137",
    },
    {
      _id: "8",
      images: product_08,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "Masstel Tab 8 Plus",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "1.890.000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Core i5",
      screen: "8.0”",
      ram: "1 GB",
      rom: "8 GB",
      pin: "4000 mAh",
      count: 1,
      danhgia: "50 đánh giá",
      hoidap: "138 hỏi đáp",
      hoi: "138",
    },

    {
      _id: "9",
      images: product_09,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "iPad Pro 12.9 2020 WI-FI 256GB",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "27999000",
      del: "29999000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "A12Z Bionic",
      screen: "12.9”",
      ram: "6 GB",
      rom: "256 GB",
      pin: "9720 mAh",
      count: 1,
      danhgia: "28 đánh giá",
      hoidap: "97 hỏi đáp",
      hoi: "97",
    },
    {
      _id: "10",
      images: product_10,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "iPad Pro 11 2020 WI-FI 512GB",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "27999000",
      del: "29999000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "A12Z Bionic",
      screen: "11.0”",
      ram: "6 GB",
      rom: "512 GB",
      pin: "7540 mAh",
      count: 1,
      danhgia: "205 đánh giá",
      hoidap: "157 hỏi đáp",
      hoi: "157",
    },
    {
      _id: "11",
      images: product_11,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "iPad Pro 12.9 2021 M1 Wi-Fi 5G 2TB",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "63999000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Apple M1",
      screen: "12.9”",
      ram: "16 GB",
      rom: "2 TB",
      count: 1,
      danhgia: "56 đánh giá",
      hoidap: "97 hỏi đáp",
      hoi: "97",
    },
    {
      _id: "12",
      images: product_12,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "iPad Pro 12.9 2021 M1 Wi-Fi 1TB",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "49.999.000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Apple M1",
      screen: "12.9”",
      ram: "16 GB",
      rom: "1 TB",
      count: 1,
      danhgia: "150 đánh giá",
      hoidap: "169 hỏi đáp",
      hoi: "169",
    },
    {
      _id: "13",
      images: product_13,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "iPad Pro 11 2021 M1 Wi-Fi 1TB",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "42999000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Apple M1",
      screen: "11.0”",
      ram: "16 GB",
      rom: "1 TB",
      count: 1,
      danhgia: "15 đánh giá",
      hoidap: "41 hỏi đáp",
      hoi: "41",
    },
    {
      _id: "14",
      images: product_14,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "iPad Pro 12.9 2021 M1 Wi-Fi 5G 128GB",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "34999000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Apple M1",
      screen: "12.9”",
      ram: "8 GB",
      rom: "128 GB",
      count: 1,
      danhgia: "61 đánh giá",
      hoidap: "145 hỏi đáp",
      hoi: "145",
    },
    {
      _id: "15",
      images: product_15,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "iPad Pro 12.9 2021 M1 Wi-Fi 128GB",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "30799000",
      del: "30999000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Apple M1",
      screen: "12.9”",
      ram: "8 GB",
      rom: "126 GB",
      count: 1,
      danhgia: "50 đánh giá",
      hoidap: "121 hỏi đáp",
      hoi: "121",
    },
    {
      _id: "16",
      images: product_16,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "iPad Pro 11 2021 M1 Wi-Fi 5G 128GB",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "26999000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Apple M1",
      screen: "11.0”",
      ram: "8 GB",
      rom: "128 GB",
      count: 1,
      danhgia: "26 đánh giá",
      hoidap: "74 hỏi đáp",
      hoi: "74",
    },
    {
      _id: "17",
      images: product_17,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "iPad Pro 11 2021 M1 Wi-Fi 128GB",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "22799000",
      del: "22999000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Apple M1",
      screen: "11.0”",
      ram: "8 GB",
      rom: "128 GB",
      count: 1,
      danhgia: "63 đánh giá",
      hoidap: "84 hỏi đáp",
      hoi: "84",
    },
    {
      _id: "18",
      images: product_18,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "iPad Mini 8.3 2021 Wi-Fi 5G 64GB",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "19990000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "A15 Bionic",
      screen: "Đang cập nhật",
      ram: "3 GB",
      rom: "64 GB",
      count: 1,
      danhgia: "20 đánh giá",
      hoidap: "41 hỏi đáp",
      hoi: "41",
    },
    {
      _id: "19",
      images: product_19,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "iPad Mini 8.3 2021 Wi-Fi 64GB",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "14990000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "A15 Bionic",
      screen: "Đang cập nhật",
      ram: "3 GB",
      rom: "64 GB",
      count: 1,
      danhgia: "109 đánh giá",
      hoidap: "215 hỏi đáp",
      hoi: "215",
    },
    {
      _id: "20",
      images: product_20,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "iPad 10.2 2021 Wi-Fi + Cellular 64GB",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "13990000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "A13 Bionic",
      screen: "10.2”",
      ram: "3 GB",
      rom: " 64 GB",
      count: 1,
      danhgia: "265 đánh giá",
      hoidap: "152 hỏi đáp",
      hoi: "152",
    },
    {
      _id: "21",
      images: product_21,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "Lenovo Tab P11 Pro WI-FI 4G 128GB",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "13190000",
      del: "14590000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Snapdragon 730G",
      screen: "11.5”",
      ram: "4 GB",
      rom: "128 GB",
      pin: "8600 mAh",
      count: 1,
      danhgia: "236 đánh giá",
      hoidap: "157 hỏi đáp",
      hoi: "157",
    },
  ]);

  // Về add cart
  const [cart, setCart] = useState([]);

  const addCart = id => {
    const check = cart.every(item => {
      return item._id !== id;
    });
    if (check) {
      const data = products.filter(product => {
        return product._id === id;
      });
      setCart([...cart, ...data]);
    } else {
      alert("The product has been added to cart.");
    }
  };

  //cart
  useEffect(() => {
    const dataCart = JSON.parse(localStorage.getItem("dataCart"));
    if (dataCart) setCart(dataCart);
  }, []);

  useEffect(() => {
    localStorage.setItem("dataCart", JSON.stringify(cart));
  }, [cart]);

  const value = {
    // sản phẩm
    products: [products, setProducts],
    // cart
    cart: [cart, setCart],
    addCart: addCart,
  };
  return (
    <DataContext.Provider value={value}>
      {" "}
      {props.children}{" "}
    </DataContext.Provider>
  );
};
