import { createContext, useState, useEffect } from "react";
import { BiChip } from "react-icons/bi";
import { IoIosPhonePortrait } from "react-icons/io";
import { FaMicrochip, FaHdd, FaWeightHanging } from "react-icons/fa";
import { MdScreenShare } from "react-icons/md";
import { CgCreditCard } from "react-icons/cg";

const product_01 = require("../../images/products/pc/img1.jpg").default;
const product_02 = require("../../images/products/pc/img2.jpg").default;
const product_03 = require("../../images/products/pc/img3.jpg").default;
const product_04 = require("../../images/products/pc/img4.jpg").default;
const product_05 = require("../../images/products/pc/img5.jpg").default;
const product_06 = require("../../images/products/pc/img6.jpg").default;
const product_07 = require("../../images/products/pc/img7.jpg").default;
const product_08 = require("../../images/products/pc/img8.jpg").default;
const product_09 = require("../../images/products/pc/img9.jpg").default;
const product_10 = require("../../images/products/pc/img10.jpg").default;
const product_11 = require("../../images/products/pc/img11.jpg").default;
const product_12 = require("../../images/products/pc/img12.jpg").default;
const product_13 = require("../../images/products/pc/img13.jpg").default;
const product_14 = require("../../images/products/pc/img14.jpg").default;
const product_15 = require("../../images/products/pc/img15.jpg").default;
const product_16 = require("../../images/products/pc/img16.jpg").default;
const product_17 = require("../../images/products/pc/img17.jpg").default;
const product_pay_01 = require("../../images/products/pay1.jpg").default;
const product_pay_02 = require("../../images/products/pay2.jpeg").default;
const product_pay_03 = require("../../images/products/pay3.jpg").default;
export const DataContext = createContext();
export const DataPC = props => {
  const [products, setProducts] = useState([
    {
      _id: "1",
      images: product_01,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "Máy tính để bàn HP Pavilion TP01-1003d i3 10105/4GB/256GB...",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "11999000",
      del: "12999000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Core i3",
      ram: "5 GB",
      rom: "256 GB",
      card: "Intel UHD Graphics",
      count: 1,
      danhgia: "1 đánh giá",
      hoidap: "30 hỏi đáp",
      hoi: "30",
    },

    {
      _id: "2",
      images: product_02,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "iMac 27” 2020 Retina 5K 3.1GHz Core i5 256GB SSD MXWT2SA/A",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "48999000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Core i5",
      screen: "27”",
      ram: "8 GB",
      card: "Không",
      count: 1,
      danhgia: "1 đánh giá",
      hoidap: "12 hỏi đáp",
      hoi: "12",
    },
    {
      _id: "3",
      images: product_03,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title:
        "AVITA Liber V14B CG i7 10510UiMac 24” 2021 Retina 4.5K M1/8-Core CPU/8-Core GPU/8GB/256GB...",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "39999000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: " Apple M1",
      screen: "24”",
      ram: "8 GB",
      rom: "256 GB",
      card: "Apple M1 GPU 8 nhân",
      count: 1,
      danhgia: "1 đánh giá",
      hoidap: "18 hỏi đáp",
      hoi: "18",
    },
    {
      _id: "4",
      images: product_04,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "Mac mini 2020 M1 512GB SSD MGNT3SA/A",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "26999000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Apple M1",
      screen: "15.6”",
      ram: "8 GB",
      card: "Apple M1 GPU 8 nhân",
      count: 1,
      danhgia: "1 đánh giá",
      hoidap: "6 hỏi đáp",
      hoi: "6",
    },
    {
      _id: "5",
      images: product_05,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "Máy tính All in one Asus M3400WUAT-BA026T R5...",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "18090000₫",
      del: "18590000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Ryzen 5",
      screen: "23.8”",
      ram: "8 GB",
      rom: "512 GB",
      card: " Radeon Graphics",
      count: 1,
      danhgia: "1 đánh giá",
      hoidap: "7 hỏi đáp",
      hoi: "7",
    },
    {
      _id: "6",
      images: product_06,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "Máy tính All in one Asus E5202WHAK-BA102T i3...",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "17490000",
      del: "17990000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Core i3",
      screen: "21.5”",
      ram: "4 GB",
      rom: "512 GB",
      card: "Intel UHD Graphics",
      count: 1,
      danhgia: "1 đánh giá",
      hoidap: "14 hỏi đáp",
      hoi: "14",
    },
    {
      _id: "7",
      images: product_07,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "Máy tính All in one Lenovo IdeaCentre AIO 3 24IIL5 i5...",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "17490000",
      del: "18090000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Core i5",
      screen: "23.8”",
      ram: "8 GB",
      rom: "256 GB",
      card: "Intel HD Graphics",
      count: 1,
      danhgia: "1 đánh giá",
      hoidap: "41 hỏi đáp",
      hoi: "41",
    },
    {
      _id: "8",
      images: product_08,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "Máy tính All in one HP 200 Pro G4 AIO NT i5-10210U/8GB/256GB...",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "17390000",
      del: "17990000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Core i5",
      screen: "21.5",
      ram: "8 GB",
      rom: "256 GB",
      card: " Radeon Graphics",
      count: 1,
      danhgia: "2 đánh giá",
      hoidap: "52 hỏi đáp",
      hoi: "52",
    },

    {
      _id: "9",
      images: product_09,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "Máy tính All In One HP 22-df1021d i3 1125G4/4GB/256GB SSD/21.5”",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "16390000",
      del: "16890000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Core i5",
      screen: "21.5”",
      ram: "4 GB",
      rom: "256 GB",
      card: "ntel UHD Graphics",
      count: 1,
      danhgia: "1 đánh giá",
      hoidap: "3 hỏi đáp",
      hoi: "3",
    },
    {
      _id: "10",
      images: product_10,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title:
        "Máy tính All in one HP 205 Pro G4 AIO NT R5 4500U/8GB/256GB/Win...",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "15790000",
      del: "16390000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Ryzen 5",
      screen: "21.5”",
      ram: "8 GB",
      rom: "256 GB",
      card: "Radeon Graphics",
      count: 1,
      danhgia: "1 đánh giá",
      hoidap: "65 hỏi đáp",
      hoi: "65",
    },
    {
      _id: "11",
      images: product_11,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "Máy tính để bàn HP Pavilion TP01 2003d i5...",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "15189000",
      del: "15689000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Core i5",
      ram: "8 GB",
      rom: "512 GB",
      card: "Đang cập nhật",
      count: 1,
      danhgia: "1 đánh giá",
      hoidap: "13 hỏi đáp",
      hoi: "13",
    },
    {
      _id: "12",
      images: product_12,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "Máy tính All In One HP 22-df1022d i3 1125G4/4GB/256GB SSD/21.5”",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "14990000",
      del: "15490000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Core i3",
      screen: "21.5”",
      ram: "4 GB",
      rom: "256 GB",
      card: "Intel UHD Graphics",
      count: 1,
      danhgia: "1 đánh giá",
      hoidap: "7 hỏi đáp",
      hoi: "7",
    },
    {
      _id: "13",
      images: product_13,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "Máy tính All In One HP 22-df0131d i3 10100T_180N4AA ",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "14690000",
      del: "15290000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Core i3",
      screen: "21.5”",
      ram: "4 GB",
      rom: "256 GB",
      card: " Intel UHD Graphics 630",
      count: 1,
      danhgia: "1 đánh giá",
      hoidap: "25 hỏi đáp",
      hoi: "25",
    },
    {
      _id: "14",
      images: product_14,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "Máy tính All in one Lenovo IdeaCentre AIO 3 24IIL5 i3...",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "14290000",
      del: "14790000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Core i3",
      screen: "23.8”",
      ram: "4 GB",
      rom: "256 GB",
      card: "Intel HD Graphics",
      count: 1,
      danhgia: "1 đánh giá",
      hoidap: "29 hỏi đáp",
      hoi: "29",
    },

    {
      _id: "15",
      images: product_15,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "Máy tính All in one Asus V222FAK-BA219T i3 10110U/4GB/256GB...",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "13590000",
      del: "13890000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Core i3",
      screen: "21.5”",
      ram: "4 GB",
      rom: "256 GB",
      card: "Intel UHD Graphics",
      count: 1,
      danhgia: "1 đánh giá",
      hoidap: "37 hỏi đáp",
      hoi: "37",
    },

    {
      _id: "16",
      images: product_16,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "Máy tính để bàn HP S01-pF1145d i5 10400/8GB/256GB/DVDWR/K/M...",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "12990000",
      del: "13290000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Core i5",
      ram: "8 GB",
      rom: "256 GB",
      card: "Intel UHD Graphics 630",
      count: 1,
      danhgia: "1 đánh giá",
      hoidap: "16 hỏi đáp",
      hoi: "16",
    },

    {
      _id: "17",
      images: product_16,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "Máy tính để bàn HP S01-pF1000d i3 10105/8GB/256GB/DVDWR/ WL...",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "12499000",
      del: "13499000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Core i3",
      ram: "8 GB",
      rom: "256 GB",
      card: "Intel UHD Graphics 630",
      count: 1,
      danhgia: "1 đánh giá",
      hoidap: "52 hỏi đáp",
      hoi: "52",
    },

    {
      _id: "18",
      images: product_11,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "Máy tính để bàn HP Pavilion TP01 1001d i3...",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "10799000",
      del: "10999000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Core i3",
      ram: "8 GB",
      rom: "256 GB",
      card: "Intel UHD Graphics 630",
      count: 1,
      danhgia: "1 đánh giá",
      hoidap: "13 hỏi đáp",
      hoi: "13",
    },

    {
      _id: "19",
      images: product_17,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "Máy tính để bàn HP M01 F1000d Pentium Gold...",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "7990000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Pentium",
      ram: "4 GB",
      rom: "256 GB",
      card: "Intel UHD Graphics 630",
      count: 1,
      danhgia: "1 đánh giá",
      hoidap: "44 hỏi đáp",
      hoi: "44",
    },

    {
      _id: "20",
      images: product_12,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "Máy tính All In One HP 24-df1032d i3 1125G4",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "7990000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Pentium",
      screen: "21.5”",
      ram: "4 GB",
      rom: "256 GB",
      card: "Intel UHD Graphics 630",
      count: 1,
      danhgia: "1 đánh giá",
      hoidap: "55 hỏi đáp",
      hoi: "55",
    },

    {
      _id: "21",
      images: product_12,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "Máy tính All In One HP 24-df1028d i5 1135G7",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "7490000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Core i5",
      screen: "23.8”",
      ram: "8 GB",
      rom: "512 GB",
      card: "Intel Iris Xe Graphics",
      count: 1,
      danhgia: "1 đánh giá",
      hoidap: "1 hỏi đáp",
      hoi: "1",
    },
    /*
    {
      _id: "22",
      images: product_12,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "Máy tính All In One HP 24-df1030d i5 1135G7",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "7990000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Core i5",
      screen: "23.8”",
      ram: "8 GB",
      rom: "512 GB",
      card: "Intel Iris Xe Graphics",
      count: 1,
    },

    {
      _id: "23",
      images: product_12,
      imgpay1: product_pay_01,
      imgpay2: product_pay_02,
      imgpay3: product_pay_03,
      title: "Máy tính All In One HP 24-df1034d i3 1125G4",
      content: "Giam thêm 500.000đ qua thẻ tín dụng FECredit",
      price: "8990000",
      installment: "Trả góp 0%",
      sale: "Gỉam 4.000.000đ",
      cpu: "Core i5",
      screen: "23.8”",
      ram: "8 GB",
      rom: "512 GB",
      card: "Intel Iris Xe Graphics",
      count: 1,
    },
    */
  ]);

  // Về add cart
  const [cart, setCart] = useState([]);

  const addCart = id => {
    const check = cart.every(item => {
      return item._id !== id;
    });
    if (check) {
      const data = products.filter(product => {
        return product._id === id;
      });
      setCart([...cart, ...data]);
    } else {
      alert("The product has been added to cart.");
    }
  };

  //cart
  useEffect(() => {
    const dataCart = JSON.parse(localStorage.getItem("dataCart"));
    if (dataCart) setCart(dataCart);
  }, []);

  useEffect(() => {
    localStorage.setItem("dataCart", JSON.stringify(cart));
  }, [cart]);

  const value = {
    // sản phẩm
    products: [products, setProducts],
    // cart
    cart: [cart, setCart],
    addCart: addCart,
  };
  return (
    <DataContext.Provider value={value}>
      {" "}
      {props.children}{" "}
    </DataContext.Provider>
  );
};
